repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.7'
    hooks:
    -   id: clang-format
-   repo: local
    hooks:
      - id: clang-tidy
        name: Run clang-tidy
        entry: clang-tidy
        language: system
        types: [c++]    # Includes .cpp and .h files
