repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.7'
    hooks:
    -   id: clang-format
        exclude: ^.vscode/
-   repo: local
    hooks:
    -   id: clang-tidy
        name: clang-tidy
        entry: pio check
        language: system
        types: [c++]    # Includes .cpp and .h files
        pass_filenames: false  # Don't pass file names to the entry point
